server:
  port: 8094

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/inventory_db
    username: root
    password: 19november2000
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: INVENTORY-SERVICE