server:
  port: 7070

  spring:
    datasource:
      url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
      username: root
      password: 19november2000
      driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      datasource-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
    application:
      name: PRODUCT-SERVICE
